### ISSUE TITLE
Unsure how to Submit on the What is a test lab

### ISSUE THREAD

**Issue by nicholasstano** [learn-co-curriculum/js-what-is-a-test-lab#10]
Hello,

On the What is a test lab I am unable to submit and move onto the next lesson.

Thanks for your help,

Nick

**Comment by maxwellbenton** [comment]
Hi @nicholasstano,

Sorry to hear you were having difficulty with this lab. Unfortunately, I was unable to replicate the issue you experienced. However, we've recently updated the contents of this lesson and, confirmed that the lesson submits as expected now. We've also added some additional instructions at the end for registering completion of the lesson.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide this feedback.

Thank you!
