### ISSUE TITLE
Cannot find module 'jsdom/lib/old-api'

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/js-what-is-a-test-lab#11]
Running `learn` on a fresh copy of this lab throws the following error message:

```
  1)  "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)
```

This is occurring in the in-browser IDE, desktop IDE, and local environment.

Reported by @SofiaIsabelle.

**Comment by ivalentine** [comment]
Looks like this is a broader issue affecting multiple JS labs. The solution is to change this line in `package.json`…

`"mocha-jsdom": "^1.1.0",`

…to this…

`"mocha-jsdom": "~1.1.0",`

…then run `npm install`.

Closing this issue.

**Comment by marysue** [comment]
Could you give us the full path where package.json resides?  When I run find . -name package.json from my working directory in my IDE I get a list of 24 distinct paths where package.json exists.

**Comment by ivalentine** [comment]
@marysue You can find `package.json` in the root directory of this lab. The name of the directory will be `js-what-is-a-test-lab-v-000` (or similar).

**Comment by howardemilya** [comment]
following the above instructions only changed my error to the following:

 1) index "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at process.nextTick (node_modules/jsdom/lib/jsdom.js:325:18)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)



npm ERR! Test failed.  See above for more details.

**Comment by reddivari9** [comment]
i have same kind of issue

1) "before all" hook:
     Error: Cannot find module 'di-components'

di-components is an external library using in html script and in webpack we mentioned di-components as external option. While running test cases i am getting  Error: Cannot find module 'di-components'
