### ISSUE TITLE
Learn.co doesn't identify that I submitted pull request

### ISSUE THREAD

**Issue by mccarronmollye** [learn-co-curriculum/js-what-is-a-test-lab#13]
Hi! I got all 3 tests to pass the typed 'learn submit' in my terminal and learn.co didn't pickup that I had sent my pull request to GitHub. I refreshed the page to see if it would update, but it did not.

**Comment by mccarronmollye** [comment]
I should also add that learn.co couldn't identify that I forked the lab, but it did see that I passed all the tests.

**Comment by rrcobb** [comment]
Hi there! This request sounds like a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
