### ISSUE TITLE
Anyway to reset the tests in OPEN IDE

### ISSUE THREAD

**Issue by nicholasstano** [learn-co-curriculum/js-what-is-a-test-lab#14]
Hello I started the curriculum last spring.  I'm getting back into it with some code already in the OPEN IDE files.  I'm wondering if there's a way for me to reset the tests so I can start over them without making a new account.

Thanks

Nick

**Comment by maxwellbenton** [comment]
Hi @nicholasstano,

If you're still working on any Learn content and want to reset your progress, from the lesson page on Learn.co, if you click the Issue Flag button, you will be brought to the unaltered canonical version of the lesson. From there, you can copy and paste whatever is in solution file (`index.js`) to get back to the original state of a lesson.
