### ISSUE TITLE
Lab will not register as "Forked", nor will it register as "Submitted"

### ISSUE THREAD

**Issue by humblescuba** [learn-co-curriculum/js-what-is-a-test-lab#7]
I have successfully passed the tests in this lab in IDE, submitted the lab, and yet my browser (Chrome) will not register the lab as either "Forked" or "Submitted". I had this problem with the previous lesson, as well, but assumed that was because the tests within the lab were purposefully left unfinished in the previous lesson. 

Thanks for your attention,

Steve

**Comment by gj** [comment]
Hi @humblescuba !

GitHub was having some webhook problems earlier. If you want to try again now, it should be all resolved: https://status.github.com/
