### ISSUE TITLE
application not doing anything when typing in Learn

### ISSUE THREAD

**Issue by ConradWill** [learn-co-curriculum/js-what-is-a-test-lab#9]

**Comment by maxwellbenton** [comment]
Hi @ConradWill,

Sorry to hear you were having difficulty with this lab. Unfortunately, I was unable to replicate the issue you experienced. However, we've recently updated the contents of this lesson and confirmed that Learn is working as intended now.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide this feedback.

Thank you!
